version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Setting Up the enviorment
          command: sudo apt-get update
      - run:
          name: Installing Maven
          command: sudo apt-get install maven
      - run:
          name: Executing the Test
          command: mvn test -DsuiteXmlFile=RegressionTest.xml
      - run:
          name: Genarating Report
          command: mvn allure:report
