version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Sudo update
          command: sudo apt-get update
      - run:
          name: Install maven
          command: sudo apt-get install maven
      - run:
          name: Test Execution
          command: mvn clean install -DsuiteXmlFile=RegressionTest.xml
      - run:
          name: Allure Report Genaration
          command: mvn allure:report